# Generated by Django 3.2.7 on 2021-09-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='in US dollars $'),
        ),
    ]
